export enum ActionTypes {
    GET_USERS = 'GET_USERS',
    GET_USER = 'GET_USER',
    CREATE_NEW_USER = 'GET_NEW_USER',
    EDIT_USER = 'EDIT_USER',
    DELETE_USER = 'DELETE_USER',
    GET_TASKS = 'GET_TASKS',
    CREATE_NEW_TASK = 'CREATE_NEW_TASK',
    EDIT_TASK = 'EDIT_TASK',
    MARK_DONE = 'MARK_DONE',
}
