export enum MutationTypes {
    SET_USERS = 'SET_USERS',
    SET_USER = 'SET_USER',
    SET_NEW_USER = 'SET_NEW_USER',
    SET_UPDATE_MESSAGE = 'SET_UPDATE_MESSAGE',
    SET_TASKS = 'SET_TASKS',
    SET_NEW_TASK = 'SET_NEW_TASK',
}
